<?php

/**
 * @file
 * Contains cucumber_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cucumber_ui_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    case 'help.page.cucumber_ui':
        $readme = __DIR__ . '/README.md';
        $text = file_get_contents($readme);
        $output = '';

        // If the Markdown module is installed, use it to render the README.
        if ($text && \Drupal::moduleHandler()->moduleExists('markdown') === true) {
            $filter_manager = \Drupal::service('plugin.manager.filter');
            $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
            $config = ['settings' => $settings];
            $filter = $filter_manager->createInstance('markdown', $config);
            $output = $filter->process($text, 'en');
        }
        // Else the Markdown module is not installed output the README as text.
        elseif ($text) {
            $output = '<pre>' . $text . '</pre>';
        }

        // Add a link to the Drupal.org project.
        $output .= '<p>';
        $output .= t(
            'Visit the <a href=":project_link">Cucumber UI project page</a> on Drupal.org for more information.', [
            ':project_link' => 'https://www.drupal.org/project/cucumber_ui',
            ]
        );
        $output .= '</p>';

        return $output;
    }

}

/**
 * Implements hook_theme().
 */
function cucumber_ui_theme($existing, $type, $theme, $path)
{

    return [
    'cucumber_ui_report' => [
      'render element' => 'children',
      'template' => 'cucumber-ui-report',
      'path' => $path . '/templates',
      'variables' => [
        'output' => t('No report yet'),
      ],
    ],
    ];

}
