cucumber_ui.settings:
  type: mapping
  label: Settings
  mapping:
    config_path:
      type: string
      label: "Cucumber configuration path"
    bin_path:
      type: string
      label: "Cucumber binary command path"
    config_file:
      type: string
      label: "Cucumber configuration file name"
    features_path:
      type: string
      label: "Cucumber Features path"
<<<<<<< HEAD
    autoload_path:
      type: string
      label: "Vendor autoload path"
=======
>>>>>>> 466cfcedbb1829601a135386b5da1c192e5c36c2
    html_report:
      type: boolean
      label: "Enable HTML report"
    html_report_dir:
      type: string
      label: "HTML report directory"
    log_report_dir:
      type: string
      label: "Log report directory"
    editing_mode:
      type: string
      label: "Editing mode"
<<<<<<< HEAD
    http_user:
      type: string
      label: "HTTP Authentication User"
    http_password:
      type: string
      label: "HTTP Authentication Password"
=======
>>>>>>> 466cfcedbb1829601a135386b5da1c192e5c36c2
    http_auth_headless_only:
      type: boolean
      label: "HTTP authentication only"
    save_user_testing_features:
      type: boolean
      label: "Save user testing features"
    needs_browser:
      type: boolean
      label: "Needs a real browser"
    cucumber_tags:
      type: string
      label: "Cucumber Tags"
