cucumber_ui.settings:
  type: mapping
  label: Settings
  mapping:
    config_path:
      type: string
      label: "Cucumber configuration path"
    config_file:
      type: string
      label: "Cucumber configuration file name"
    features_path:
      type: string
      label: "Cucumber Features path"
    html_report:
      type: boolean
      label: "Enable HTML report"
    html_report_dir:
      type: string
      label: "HTML report directory"
    log_report_dir:
      type: string
      label: "Log report directory"
    editing_mode:
      type: string
      label: "Editing mode"